server:
  port: 12000


swagger:
  enabled: true
  title: 测试服务中心
  serverUrl:
  version: 0.1

jwt:
  header: Authorization
  # ????
  token-start-with: Bearer
  secret: k03HQfaW
  # ??????88??Base64????????
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # ?????? ????/?? ???4?????????? https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # ????key
  online-key: online-token
  # ???? ??????key
  curruser-key: curruser-key
  # ???
  code-key: code-key
